### ISSUE TITLE
VIP用户的128M流量是啥意思啊？

### ISSUE THREAD

**Issue by KuiWei004** [leanote/leanote.com-issue#106]
如题，，，，，

**Comment by lealife** [comment]
每月/128M. 图片,附件,笔记上传的流量

**Comment by zhouxin-tim** [comment]
超级不够用，我只是对文档进行修改，没有变动很多，流量就会猛的往上涨，我那个文档越大涨的越多

**Comment by zhouxin-tim** [comment]
那我如果有个10M的文档修改保存个十多次就用完了超级不合理

**Comment by zhouxin-tim** [comment]
我修改保存一个文档一下增加我10多M流量！！！！！这还怎么用！！！！
