### ISSUE TITLE
图片保存不同步问题

### ISSUE THREAD

**Issue by SoulFeeling** [leanote/leanote.com-issue#113]
本地环境：服务搭建以默认localhost:9000开启服务，并通过nginx 转发将指定域名映射到 localhost:9000 开始对外服务，
问题：
       在win7PC客户端新建笔记中并保存一张图片，同步到服务上，然后在在网页打开显示无效图片；
       同样在网页编辑中新添一张图片，同步服务后，在pc打开也是显示无效图片

服务域名：http://note.liuxiaoge.com/

**Comment by cheerconi** [comment]
遇到了同样的问题，根据 https://github.com/leanote/leanote.com-issue/issues/74 解决了。

**Comment by yu2lulu** [comment]
> 遇到了同样的问题，根据 #74 解决了。

你的是https的吗，还是http的？
