### ISSUE TITLE
太多缺陷了，只能算个半成品

### ISSUE THREAD

**Issue by ahxx615** [leanote/leanote.com-issue#120]
刚用了半天，就发现了两个缺陷，你们开发测试吃屎的吗。
1.点击编辑按钮跳回首行。
2.插入代码框后，如果你想在下面接着写常规文字，没法选中下一行。

**Comment by ahxx615** [comment]
还好只买了3个月

**Comment by ahxx615** [comment]
还有你们连个中文网站都做不起吗？

**Comment by lealife** [comment]
如何跳出代码框? http://leanote.leanote.com/post/get-out-of-code-block
点击编辑按钮跳回首行, 问题不存在
