### ISSUE TITLE
晚上改了四篇很简短的文本笔记，十几分钟过去了，还在更新着呢?!

### ISSUE THREAD

**Issue by shenj520** [leanote/leanote.com-issue#152]
本来买高级会员就想图个简单实用，万万没想到，晚上改了四篇很简短的文本笔记（总计不足2000字），十几分钟过去了，还在更新着呢?!无奈退出帐户，重新登录，这才ok，这钱你们收的安心吗？

**Comment by shenj520** [comment]
怪我太相信你们了，再见！

**Comment by lealife** [comment]
可能同步出错
