### ISSUE TITLE
开发一个导入有道云笔记的工具

### ISSUE THREAD

**Issue by niaiwomattt** [leanote/leanote.com-issue#154]
如果能开发一个导入有道云笔记的工具，我就买个旗舰套餐。因为我的笔记都在有道云笔记，但是我导出不了，如果能开发一个工具，直接导入到蚂蚁笔记就好了。

**Comment by lealife** [comment]
有道云笔记不支持导出(导出后是加密的数据), 所以无法导入到Leanote
