### ISSUE TITLE
右侧新建一个笔记本不能同步的bug

### ISSUE THREAD

**Issue by skyhiter** [leanote/leanote.com-issue#18]
os: win7 x64 SP1
leanote: v2.5 x64
描述：
客户端右侧新建一个笔记本IR-Learning，但是 该“笔记本名“迟迟未同步，还是显示一个红色小圆点。即使在设置里点强制同步，仍然不能同步到服务器。
![image](https://user-images.githubusercontent.com/3953193/28492537-3596f8a0-6f38-11e7-9b3a-5aaf74f3a4ce.png)

**Comment by Yindaxian** [comment]
不知道你说的**强制同步**是不是那个**强制全量同步**.
**强制全量同步**的提示上写的是删除所有本地数据,重新下载一份笔记数据,不是把你的更新同步到服务器.
你如果正常同步没成功的话,全量好像也是没用的.

**Comment by skyhiter** [comment]
多谢，是我等了几天都不能将本地新建的笔记本同步到服务器，我才尝试“强制全量同步”，正如你说，它是从服务器download覆盖local. 不过这跟我问的问题没啥关系。 = . =
