### ISSUE TITLE
Leanote无法备份数据

### ISSUE THREAD

**Issue by Torah** [leanote/leanote.com-issue#215]
登陆管理员去备份数据的时候，会报错如下：
![image](https://user-images.githubusercontent.com/6466559/63000474-d2608b80-bea3-11e9-9378-b03e23c69b69.png)
试过很多台机器都是这样，不清楚Linux的问题还是Leanote的bug?

**Comment by michaelhu-space** [comment]
同问

**Comment by cngege** [comment]
点data下的第一个子项,设置相关mongorestore路径就可以备份 恢复了

**Comment by luanlibao** [comment]
这个我会搞。。。
我用的是群晖Docker建的Leanote，
进容器的终端，执行 ` whereis mongodump ` 、 `whereis mongorestore` ，
会得到俩路径，
然后用admin进Leanote后台，点Data，第一个里面填上两个对应的路径。。。然后你再试试～

**Comment by Torah** [comment]
哇，你好牛！
原来是要设置mongodb，不是linux的问题。
顺利完成。
