### ISSUE TITLE
以前保存的文件怎么图片都不能看了啊

### ISSUE THREAD

**Issue by w935903854** [leanote/leanote.com-issue#222]
![image](https://user-images.githubusercontent.com/59118285/71309530-c1bcb500-2443-11ea-870b-bda758da42e9.png)
图片现在全部没有了,这样该怎么解决啊,有点失望!

**Comment by power321** [comment]
同问，开了会员都没用，失望

**Comment by lukhap** [comment]
图片呢图片呢？

**Comment by w935903854** [comment]
不好意思  我那个图片保存的是网络地址,那个网络地址失效了所以我这边就显示不出来了,我还以为都丢了呢.

**Comment by 1253757553** [comment]
我的图片也消失了，这是开了会员的待遇么？
