### ISSUE TITLE
云协作功能 空间无法删除

### ISSUE THREAD

**Issue by ConanCCC** [leanote/leanote.com-issue#229]
开了个空间发现问题很大，打算改名字，发现改不了。
打算把空间改权限为私有，也改不了。
最后想把空间删掉，也删不了。
这有点难顶啊，空间不能修改删除吗？

**Comment by lealife** [comment]
![image](https://user-images.githubusercontent.com/1699428/129433251-e4f0ab05-bb43-4872-88d3-be4272e2a4c4.png)
