### ISSUE TITLE
关于博客的问题

### ISSUE THREAD

**Issue by splEnough** [leanote/leanote.com-issue#28]
我要怎么修改我的博客的信息？

**Comment by Yindaxian** [comment]
我是这么进的,不知道有没有一步进入个人中心的方法.
1. [leanote官网](www.leanote.com)
2. 登陆后,右上角头像旁的下拉菜单,选**我的笔记**.
3. 在笔记页面右上角,头像旁的下拉菜单,选**博客设置**.
4. 左侧菜单可以设置博客信息.

**Comment by lealife** [comment]
@Yindaxian 只有这个方法
