### ISSUE TITLE
Markdown编辑模式下，有序列表序号bug

### ISSUE THREAD

**Issue by dongxurr123** [leanote/leanote.com-issue#34]
每个有序列表中间有比较大段的代码段，序号会重新开始计算。
版本：Linux-x64-2.5、网页版也存在这个问题
看图：
![_ _20170809184439](https://user-images.githubusercontent.com/2542795/29118228-a6fca5cc-7d33-11e7-9bfd-36db527742b8.png)

**Comment by lealife** [comment]
你好, Markdown语法就是这样的, 相同的序号必须在相邻行
