### ISSUE TITLE
内容无法保存，且无任何错误提示，让人错觉已保存成功。文章显示更新时间一直为2017-08-08 22:23:09秒！

### ISSUE THREAD

**Issue by dongxurr123** [leanote/leanote.com-issue#36]
今天晚上8点过，在原有文档加了点东西。回到家再打开，又变成修改前的样子。
随后进行两个场景测试
1. 再次修改，关闭leanote，再次打开，又变成修改前的样子。
2. 新增一篇博客题目为：《test-lost》，ctrl+s保存，左下角进度条闪过，从视觉上我认为是保存成功了，关闭leanote，再次打开，文章消失。登录网页版查看，测试文章没有增加。

## **个人认为这是一个非常严重的bug！请重视**

版本：linux-x64-2.5
文章题目：《供应链部门后端java代码规范》，应该能从后台根据题目查询。

**Comment by lealife** [comment]
谢谢, 我们会排序linux桌面端问题

**Comment by dongxurr123** [comment]
账号：dongxurr123@163.com

**Comment by wanicca** [comment]
同！！！突然出现这样的问题，似乎是更新2.5之后才有的。
系统为Manjaro。
表现为：已存在的笔记修改保存后，重新打开发现保存并未成功，网页端打开依然是原来的。
新建笔记保存后，如果我点开别的笔记再重新打开，就会卡在加载内容，笔记内容不出现，重启客户端这个笔记就消失了！在网页端查看发现这个笔记并不存在。

因为这个原因我写的一段很长的文字没有保存下来，非常让人生气，还得重新写一遍。

**Comment by dongxurr123** [comment]
@lealife 
我似乎知道原因了。
Linux下，Leanote无法用普通用户更新，从2.4更新到2.5的时候，我是用root启动并更新的。随后再用普通用户打开，便出现了如题所述的问题。今天我尝试又用root启动，再对文件进行编辑，更新保存成功！！
即使是由于root用户启动过leanote导致的，我觉得leanote的产品体验是个问题，最大的问题是”异常对用户不透明“。如果保存不成功，或者有啥问题，最起码应该弹个框给用户提示一下吧？！
给用户展示的动画效果是 保存成功的，但最终却没保存，用户辛辛苦苦编辑了个把小时的东西说没就没，那谁还敢用？！？！我相信leanote的收费版也有这类问题。

**Comment by dongxurr123** [comment]
@wanicca  看看是不是因为起那一次用 root启动过。

**Comment by wanicca** [comment]
@dongxurr123 并不是这个原因，我换了新电脑，重新安装，依然有这个问题，但是从root启动可以保存没有问题，这种状况几个月以来一直没有解决。
我今天突然发现客户端可以打开chrome的调试器，就打开看了一眼，发现一开始载入tinymce脑图插件时报错了，提示找不到文件，于是去文件夹下找了找，发现不知道什么原因这个插件文件夹的权限是只有root用户可读写，其他用户不可读不可执行。
于是chmod一下，保存功能终于恢复了正常。
