### ISSUE TITLE
增加记账功能

### ISSUE THREAD

**Issue by logic-wei** [leanote/leanote.com-issue#58]
# 想法
基于markdown语法，加一个绘制账单的功能，使用非常方便，可以取代一大批的记账软件。
# 实现
我自己写了个python脚本，用来分析账单数据然后绘制出来，账单格式大概如下：
```markdown
# 2017年
## 1月
### 1日
早餐 -10
午餐 -20
```
每次我都是从笔记里面拷贝出来再用python分析，这样很麻烦，然后萌生了自己开发leanote的想法，尝试了下，对我来说还是比较困难，所以希望leanote官方能够加入此功能，或者开放一些插件API降低我们的开发难度也不错。

**Comment by lealife** [comment]
.... 暂时不会实现
