### ISSUE TITLE
在火狐浏览器上使用蚂蚁笔记，文档导航有问题

### ISSUE THREAD

**Issue by zhang555** [leanote/leanote.com-issue#66]
点击文档导航中的标签，如果是纯英文，可以正常跳转
如果带有中文，就不会跳转。。

**Comment by wangduanduan** [comment]
我是mac, 用chrome62浏览器。点击了导航菜单也是没有反应，即使菜单中标题中都是纯英文，点了也是无反应。 我我发现，点击之后，并没有执行scrollTo方法。

**Comment by kentcc88** [comment]
试试去掉网页缓存！

**Comment by lealife** [comment]
已修复

**Comment by atsz** [comment]
当前官方版本，在Chrome72.版本上，点击导航没反应
