### ISSUE TITLE
leanote 自己架设的服务器不能同步大于 3m 的附件是什么情况？

### ISSUE THREAD

**Issue by jsjcjsjc** [leanote/leanote.com-issue#68]
架设完之后，其他测试我看都没问题。。就是稍微大一点的附件就不能同步，提示网络有无问题，删除附件就可以了~~

**Comment by jsjcjsjc** [comment]
原来是nginx 默认大小是1m~~~

**Comment by kingteng** [comment]
然后你会发现会有10M的限制，不知道怎么改，但是也够用了，偶尔遇到不够就分包
