### ISSUE TITLE
私有部署图片不能同步的问题解决方法

### ISSUE THREAD

**Issue by wangdanaadf** [leanote/leanote.com-issue#74]
看到很多人说这个问题，新人，不知道以前有没有类似的issue，如果重复了请告知。

原因：图片在同步的时候，链接是
> http://xxxx.xx:9000/api/file/getImage?fileId=xxxxxxxxxxxxxxx
图片不显示一般都是你的域名没有配置好

- 1 在服务器配置文件中有一条

> site.url=http://localhost:9000

把localhost改成你自己的域名
- 2 另一种方法，原理一样，以admin用户名登录，默认密码是abc123，然后在后台管理，configuration，Site's URL,设置你的域名

**Comment by wangdanaadf** [comment]
有同学说配置了域名，局域网可能无法连接，可以在路由器里设置局域网中域名解析

我自己用的openwrt的路由器，其他的路由器自己找设置吧，原理是一样的

> 在 网络 \> 主机名 中设置主机名为你的域名，ip为服务器的内网ip

**Comment by cheerconi** [comment]
感谢，遇到同样的问题，按照你的方法解决了。

**Comment by lealife** [comment]
https://github.com/leanote/leanote/wiki/QA 有相关问题的解决

**Comment by ericxuyihao** [comment]
Thanks for your suggestion.The problem is solved.

**Comment by yu2lulu** [comment]
> 看到很多人说这个问题，新人，不知道以前有没有类似的issue，如果重复了请告知。
> 
> 原因：图片在同步的时候，链接是
> 
> > http://xxxx.xx:9000/api/file/getImage?fileId=xxxxxxxxxxxxxxx
> > 图片不显示一般都是你的域名没有配置好
> 
> * 1 在服务器配置文件中有一条
> 
> > site.url=http://localhost:9000
> 
> 把localhost改成你自己的域名
> 
> * 2 另一种方法，原理一样，以admin用户名登录，默认密码是abc123，然后在后台管理，configuration，Site's URL,设置你的域名

https的也使用吗？

**Comment by ericxuyihao** [comment]
您好:
       如果配置域名那么通过域名访问可以获取图片.但是在家庭网络中(电信光纤) 只能通过IP地址访问(192.168.1.XXX:XXXX)这样就获取不到图片. 那么这样就导致显示不了域名地址的图片了.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Jeffery.Yu <notifications@github.com>
发送时间: Tuesday, June 4, 2019 2:48:59 PM
收件人: leanote/leanote.com-issue
抄送: eric; Comment
主题: Re: [leanote/leanote.com-issue] 私有部署图片不能同步的问题解决方法 (#74)


看到很多人说这个问题，新人，不知道以前有没有类似的issue，如果重复了请告知。

原因：图片在同步的时候，链接是

http://xxxx.xx:9000/api/file/getImage?fileId=xxxxxxxxxxxxxxx
图片不显示一般都是你的域名没有配置好

  *   1 在服务器配置文件中有一条

site.url=http://localhost:9000

把localhost改成你自己的域名

  *   2 另一种方法，原理一样，以admin用户名登录，默认密码是abc123，然后在后台管理，configuration，Site's URL,设置你的域名

https的也使用吗？

―
